Images
IBM/tjbot-sports-buddy pull request #14
Opened 2017-05-23 20:02 UTC by stevemart

2017-05-23 20:02 UTC, stevemart commented on README.md
> -them at [https://www.twilio.com/console/phone_numbers/verified](https://www.twilio.com/console/phone_numbers/verified).
this link didn't work for me if i didn't have any phone numbers yet.

2017-05-23 20:26 UTC, rhagarty requested changes
Just the one suggestion. Nice pics, btw

2017-05-23 20:26 UTC, rhagarty commented on README.md
> +You may need to install dependencies before running the application, to do
I think we need to add this in the line above run.js. This will ALWAYS be needed.

2017-05-23 21:19 UTC, stevemart commented
@rhagarty addressed your comments, refer to latest change set

2017-05-24 03:53 UTC, rhagarty approved these changes

2017-05-24 03:53 UTC, merged